trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # e.g., name of your ACR
  acrName: 'mydevopsdummyacr'
  # Docker Compose version or single Docker tasks

steps:
- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    containerRegistry: 'MyContainerRegistryServiceConnection'
    command: 'login'

# Build & push BACKEND
- task: Docker@2
  displayName: 'Build & push backend'
  inputs:
    containerRegistry: 'MyContainerRegistryServiceConnection'
    repository: 'backend' # The name of your image
    command: 'buildAndPush'
    Dockerfile: 'backend/Dockerfile'
    tags: |
      latest
    tags: |
      $(Build.BuildId)

# Build & push FRONTEND
- task: Docker@2
  displayName: 'Build & push frontend'
  inputs:
    containerRegistry: 'MyContainerRegistryServiceConnection'
    repository: 'frontend' # The name of your image
    command: 'buildAndPush'
    Dockerfile: 'fronten/Dockerfile'
    tags: |
      latest
    tags: |
      $(Build.BuildId)
