version: "3.9"
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: mydevopsdummyacr.azurecr.io/devopsdummy-backend:latest
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  frontend:
    build:
      context: ./fronten
      dockerfile: Dockerfile
    image: mydevopsdummyacr.azurecr.io/devopsdummy-frontend:latest
    ports:
      - "3000:80"
